### ISSUE TITLE
Why is this so brilliant?

### ISSUE THREAD

**Issue by desmondlzy** [SsparKluo/cu_calendar#1]
Well I come across this project just now and I feel it's really helpful to have this sort of tool. But really, one little question has been staying in my mind...

Why is this project (and the guy who wrote this) so darn brilliant?

**Comment by SsparKluo** [comment]
???

**Comment by desmondlzy** [comment]
And I feel great honor to be the first one to give this project a star

**Comment by SsparKluo** [comment]
aini.jpg

**Comment by desmondlzy** [comment]
no, ni bu ai wo
